Remove ROM files and links to BIOS files
joshcampbell191/openfpga-cores-inventory pull request #10
Opened 2022-09-24 04:44 UTC by goronfreeman

Closes #9

2022-09-24 10:25 UTC, joshcampbell191 commented on _data/cores.yml
>          - file_name: asteroid.rom
If we're removing ROM files, should we still list them? I can understand why we'd want to list BIOS files as they're required in order to launch the ROMs.

2022-09-24 23:16 UTC, goronfreeman commented on _data/cores.yml
>          - file_name: asteroid.rom
I added some more thoughts in #9, but my thinking here is that since certain cores require a specific ROM file to be functional (as opposed to something like the SNES core where a lot of different ROMs can be used), it would be worth listing them in the API. The Asteroids core won't work at all unless there is the specific file `asteroid.rom` placed in `Assets/asteroids/ericlewis.Asteroids/`.

2022-09-24 23:25 UTC, goronfreeman commented on _data/cores.yml
> +            checksum: ""
The link for the Dominos ROM was no longer functional. @RetroDrive, could you provide me the checksum for this file?

2022-09-24 23:27 UTC, goronfreeman commented on _data/cores.yml
> +            checksum: ""
The link for the Dominos ROM was no longer functional. @RetroDriven, could you provide me the checksum for this file?

2022-09-26 16:02 UTC, goronfreeman commented
@joshcampbell191 I think this is ready for a review. When you get time to look at it, could you double check that I got all the `platform` values correct? I checked these myself, but I want to make sure these are right. It would also be great if you could double check the checksums and validate they are correct.

2022-09-27 01:23 UTC, joshcampbell191 commented on _data/cores.yml
> +          checksum: 1bcd2899e3f92d2824a2ac9def2d3286
I know this is being nitpicky, but should we include the rom files for cores that only support a single ROM (asteroids, dominos, xevious, lunarlander, super breakout)?

2022-09-27 01:48 UTC, goronfreeman commented on _data/cores.yml
> +          checksum: 1bcd2899e3f92d2824a2ac9def2d3286
Just to make sure I understand, you mean like the lines you commented on above? I think it would be helpful to include them, as it might allow for a better user experience getting these cores set up. The user can be prompted for a specific file, and the file could be validated using the checksum.

Where it gets a little weird is with cores like Xevious. It actually supports a handful of specific ROM files. The same is true of some of the other arcade cores as well. I'm not sure if that means we should keep a list of all of them or not... 

I'm actually not sure the best way to deal with these, now that I think about. It definitely provides some value, but it also may be hard to maintain. What are your thoughts?

2022-09-27 13:10 UTC, joshcampbell191 commented on _data/cores.yml
> +          checksum: 1bcd2899e3f92d2824a2ac9def2d3286
There's definitely value for the tools to have access to this information however it does become more difficult to maintain. I'm personally not a fan of having the ROMs listed in the API for that reason. I know it might not be a popular decision amongst the community however I feel it's the right choice.

2022-09-27 19:10 UTC, goronfreeman commented on _data/cores.yml
> +          checksum: 1bcd2899e3f92d2824a2ac9def2d3286
I think you're probably right here. I think we can actually defer this to the conversation on MRA files, as that would take care of this same use case. I removed the ROM entries for now.

2022-09-27 19:26 UTC, goronfreeman commented on README.md
> +| core (optional)   | object array | A list of file objects. These files are required by the core and placed in the `Assets/<platform>/<identifier>` directory. |
Now that I removed all the ROM entries from the YAML, there are no longer any files that need to be stored here. The only cores that require additional files are GB/GBC, GBA, and NeoGeo. All the cores that can play ROM files, aside from a few arcade cores that use `Assets/<platform>/<identifier>`, use the `common` directory. Do we want to add an attribute to tell where ROMs should be placed for cores that don't use `common`?

2022-09-28 03:04 UTC, joshcampbell191 commented on README.md
> +| core (optional)   | object array | A list of file objects. These files are required by the core and placed in the `Assets/<platform>/<identifier>` directory. |
Let's wait and see what @mattpannella and @RetroDriven have to say in the other thread. It sounds like a good idea though!

2022-09-28 03:19 UTC, RetroDriven commented on README.md
> +| core (optional)   | object array | A list of file objects. These files are required by the core and placed in the `Assets/<platform>/<identifier>` directory. |
I think that's a good idea. I believe there are some Cores that have their Roms stored in a non-traditional folder.

2022-10-01 03:33 UTC, goronfreeman commented
@joshcampbell191 I applied the latest changes we discussed in #9 to this PR. I left several comments in `cores.yml` with some questions we need to figure out, but once we're good on those, I'll update the documentation, then hopefully we can get this merged!

2022-10-01 06:21 UTC, goronfreeman commented on _data/cores.yml
>        identifier: Spiritualized.GBC
I realized that there is an issue with supplying `identifier` at the top level like we have been. In the case of the GB/GBC core, there are two separate identifiers, one for each core:
- `Spiritualized.GB`
- `Spiritualized.GBC`

I'm thinking maybe instead of doing this, we provide the `AuthorName` (Spiritualized) and `CoreName` (GB or GBC) as fields that can then be used to construct the asset path. I'm not sure exactly where we should put these, but wanted to get this written down before I head to bed.

2022-10-01 15:05 UTC, joshcampbell191 commented on _data/cores.yml
> +      # Do we need assets at all if no additional files are required?
I think an empty array would be best here.

```suggestion
      assets: []
```

2022-10-01 15:27 UTC, joshcampbell191 commented on _data/cores.yml
> +        - json
The JSON files (see here: https://github.com/Mazamars312/Analogue_Pocket_Neogeo/tree/main/src/neogeojsonmaker/Game.json) are used to load the individual files (prom, m1rom, crom0, srom and vroma0) that make up the NeoGeo ROMs rather than having to load each one individually. I believe it's safe to leave out the JSON entry for assets marked as "Instance JSON" since they'll most likely be included with the cores.

2022-10-01 15:43 UTC, joshcampbell191 requested changes
Let me know if you have any questions / comments regarding any of the comments and suggestions I left below.

2022-10-01 15:43 UTC, joshcampbell191 commented on _data/cores.yml
> +        - json
Can be removed for the same reason as NeoGeo.

2022-10-01 15:43 UTC, joshcampbell191 commented on _data/cores.yml
> +        - json
Can be excluded for the same reason as NeoGeo.

2022-10-01 15:43 UTC, joshcampbell191 commented on _data/cores.yml
> +        - json
Can be excluded for the same reason as NeoGeo.

2022-10-01 15:43 UTC, joshcampbell191 commented on _data/cores.yml
> +        - json
Can be excluded for the same reason as NeoGeo.

2022-10-01 15:43 UTC, joshcampbell191 commented on _data/cores.yml
> +      # Do we want to handle these differently?
I would leave them as-is for consistency.

2022-10-01 15:43 UTC, joshcampbell191 commented on README.md
> +              "checksum": "32fbbd84168d3482956eb3c5051637f5"
Are we going to be removing checksum? If so, we can remove it from examples / documentation.

2022-10-01 15:43 UTC, joshcampbell191 commented on _data/cores.yml
>        identifier: Spiritualized.GBC
This one again... lol. 

I was thinking that we could potentially split this into two entries pointing to the same repository with a separate identifier and assets.

2022-10-01 17:14 UTC, goronfreeman commented on _data/cores.yml
>        identifier: Spiritualized.GBC
Yeah, I think that's probably the best idea too. I think that will make it a lot clearer as to what's actually going on too.

2022-10-01 17:38 UTC, mattpannella commented on _data/cores.yml
>        identifier: Spiritualized.GBC
+1 for just splitting them into separate entries. no matter what having 2 cores in the same repo is gonna be a little clunky and/or require an annoying bandaid to handle, but I think just listing each core separately like all the others makes a lot more sense

2022-10-01 18:30 UTC, joshcampbell191 commented on README.md
> +| Field         | Type    | Description
We should add a column to denote optional fields (ex. `filename` and `extensions`)? We could also add a note specifying that `filename` or `extensions` or both will be provided.

2022-10-01 18:30 UTC, joshcampbell191 approved these changes

2022-10-01 18:41 UTC, merged