Add GitHub Actions workflow
joshcampbell191/openfpga-cores-inventory pull request #16
Opened 2022-10-01 03:35 UTC by goronfreeman

This PR adds a new [GitHub Actions](https://docs.github.com/en/actions) workflow to automate the generation of the `cores.yml` file.

2022-10-01 06:32 UTC, goronfreeman commented
@joshcampbell191 I have some good news about the future maintainability of `cores.json`! With the code I have so far, I have demonstrated that we can pretty much fully automate the updating of the YAML. There are two small caveats:

1. We still need to manually add repos for new cores
2. Our current convention for `display_name` can't be automated from the available data

For 2, I think we can probably use the data we do have available to make a nice `display_name` automatically, so we should think about that a bit.

2022-10-01 14:48 UTC, joshcampbell191 commented
We could potentially have a separate data file that only includes the repositories and `display_name` and from there, it would generate the `cores.json`.

2022-10-01 14:49 UTC, joshcampbell191 commented
FYI you can test the GitHub Actions locally using [act](https://github.com/nektos/act).

2022-10-04 00:31 UTC, goronfreeman commented
@joshcampbell191 I think this is ready for a review. I left two `TODO` notes in the code that I'd like to pick your brain on:

1. How do we want to handle versions? Should we always list the most recent version, even if it's a prerelease?
2. Ostensibly the `platform_ids` entry in a core's `core.yml` file can contain multiple platforms, however it doesn't seem like any of the currently released cores have more than one. Think it's fine to punt on this?

2022-10-04 23:48 UTC, goronfreeman commented on .github/workflows/data_generator.rb
> +    def normalize_version(version)
Now that I think about it more, maybe this doesn't make sense. Maybe we just keep what the core gives us?

2022-10-05 01:17 UTC, joshcampbell191 requested changes

2022-10-05 01:17 UTC, joshcampbell191 commented on .github/workflows/data_generator.rb
> +        "version"      => normalize_version(metadata["version"]),
- As discussed, I think it might make more sense to use the version from GitHub instead. Do you agree?
- Do we want to display the latest pre-release date as well?

2022-10-05 01:17 UTC, joshcampbell191 commented on analogue-pocket.md
> +          <td data-order="{{ core.version }}">
The ordering here was kind of weird since it didn't match the versions displayed in the UI. I was thinking that we could display the actual values (the ones coming from GitHub and not from the actual core) instead of the images. What do you think?

2022-10-05 02:01 UTC, goronfreeman commented on .github/workflows/data_generator.rb
> +      system("unzip -q #{file_name} -d #{dir_name}")
Thanks for pointing this out. I was meaning to do this, but got lazy, ha.

2022-10-05 02:02 UTC, goronfreeman commented on .github/workflows/regenerate-core-yaml.yml
> +        file_pattern: '_data/*.yml'
I want this to also format `repos.yml` to keep it consistent. Probably wouldn't hurt to just blanket format the YAML files in that directory for consistency IMO.

2022-10-05 02:18 UTC, goronfreeman commented on .github/workflows/data_generator.rb
> +        "version"      => normalize_version(metadata["version"]),
This one kind of sucks. Here is an example response from the GitHub API:

```ruby
{
  "url" => "https://api.github.com/repos/agg23/analogue-arduboy/releases/76213697",
  "assets_url" => "https://api.github.com/repos/agg23/analogue-arduboy/releases/76213697/assets",
  "upload_url" => "https://uploads.github.com/repos/agg23/analogue-arduboy/releases/76213697/assets{?name,label}",
  "html_url" => "https://github.com/agg23/analogue-arduboy/releases/tag/0.9.0",
  "id" => 76213697,
  "author" => {
    "login" => "agg23",
    "id" => 238679,
    "node_id" => "MDQ6VXNlcjIzODY3OQ==",
    "avatar_url" => "https://avatars.githubusercontent.com/u/238679?v=4",
    "gravatar_id" => "",
    "url" => "https://api.github.com/users/agg23",
    "html_url" => "https://github.com/agg23",
    "followers_url" => "https://api.github.com/users/agg23/followers",
    "following_url" => "https://api.github.com/users/agg23/following{/other_user}",
    "gists_url" => "https://api.github.com/users/agg23/gists{/gist_id}",
    "starred_url" => "https://api.github.com/users/agg23/starred{/owner}{/repo}",
    "subscriptions_url" => "https://api.github.com/users/agg23/subscriptions",
    "organizations_url" => "https://api.github.com/users/agg23/orgs",
    "repos_url" => "https://api.github.com/users/agg23/repos",
    "events_url" => "https://api.github.com/users/agg23/events{/privacy}",
    "received_events_url" => "https://api.github.com/users/agg23/received_events",
    "type" => "User",
    "site_admin" => false
  },
  "node_id" => "RE_kwDOH4F_ZM4Eiu3B",
  "tag_name" => "0.9.0",
  "target_commitish" => "master",
  "name" => "Initial release",
  "draft" => false,
  "prerelease" => false,
  "created_at" => "2022-09-03T20:43:41Z",
  "published_at" => "2022-09-03T20:45:09Z",
  "assets" => [{
    "url" => "https://api.github.com/repos/agg23/analogue-arduboy/releases/assets/76786479",
    "id" => 76786479,
    "node_id" => "RA_kwDOH4F_ZM4Ek6sv",
    "name" => "agg23.Arduboy.0.9.0.zip",
    "label" => nil,
    "uploader" => {
      "login" => "agg23",
      "id" => 238679,
      "node_id" => "MDQ6VXNlcjIzODY3OQ==",
      "avatar_url" => "https://avatars.githubusercontent.com/u/238679?v=4",
      "gravatar_id" => "",
      "url" => "https://api.github.com/users/agg23",
      "html_url" => "https://github.com/agg23",
      "followers_url" => "https://api.github.com/users/agg23/followers",
      "following_url" => "https://api.github.com/users/agg23/following{/other_user}",
      "gists_url" => "https://api.github.com/users/agg23/gists{/gist_id}",
      "starred_url" => "https://api.github.com/users/agg23/starred{/owner}{/repo}",
      "subscriptions_url" => "https://api.github.com/users/agg23/subscriptions",
      "organizations_url" => "https://api.github.com/users/agg23/orgs",
      "repos_url" => "https://api.github.com/users/agg23/repos",
      "events_url" => "https://api.github.com/users/agg23/events{/privacy}",
      "received_events_url" => "https://api.github.com/users/agg23/received_events",
      "type" => "User",
      "site_admin" => false
    },
    "content_type" => "application/x-zip-compressed",
    "state" => "uploaded",
    "size" => 257119,
    "download_count" => 2515,
    "created_at" => "2022-09-03T21:27:08Z",
    "updated_at" => "2022-09-03T21:27:09Z",
    "browser_download_url" => "https://github.com/agg23/analogue-arduboy/releases/download/0.9.0/agg23.Arduboy.0.9.0.zip"
  }],
  "tarball_url" => "https://api.github.com/repos/agg23/analogue-arduboy/tarball/0.9.0",
  "zipball_url" => "https://api.github.com/repos/agg23/analogue-arduboy/zipball/0.9.0",
  "body" => "Arduboy for Analogue Pocket. Originally ported from MiSTer with substantial upgrades.",
  "reactions" => {
    "url" => "https://api.github.com/repos/agg23/analogue-arduboy/releases/76213697/reactions",
    "total_count" => 3,
    "+1" => 3,
    "-1" => 0,
    "laugh" => 0,
    "hooray" => 0,
    "confused" => 0,
    "heart" => 0,
    "rocket" => 0,
    "eyes" => 0
  }
}
```

The only thing in there that gives us the version is the `tag_name`, but as we discussed earlier, this might not reliably always be the version number. Let me know if you see anything else in there that I may have missed.

2022-10-05 02:21 UTC, goronfreeman commented on .github/workflows/data_generator.rb
> +        "version"      => normalize_version(metadata["version"]),
For release vs pre-release, the only real way that I can see to do this is if we decide we can get the version from this response. If not, then we'd have to go through the whole process of downloading even more ZIPs and parsing more JSON just to get at the version, and I can see that becoming a total mess.

Either way, I think adding a `prerelease: true` to any versions that are prerelease would be a good idea. The current updaters allow skipping pre-releases already, and I can see that being very useful.

2022-10-05 02:22 UTC, goronfreeman commented on .github/workflows/data_generator.rb
> +        "date_release" => metadata["date_release"],
See the API response below. Do you think the `published_at` value is what we would want for this?

2022-10-05 02:25 UTC, goronfreeman commented on analogue-pocket.md
> +          <td data-order="{{ core.version }}">
I had actually done this, then removed it, so we could discuss it first 😀. Shields.io actually allows for fully custom badges, so if we wanted to still show a nice badge, we can use this format: `https://img.shields.io/badge/<LABEL>-<MESSAGE>-<COLOR>`. With the pre-release info, we could even color those ones differently like they are currently displayed. If we don't care about the badge, we could also just format the date nicely and put it there.

2022-10-05 02:25 UTC, goronfreeman commented on analogue-pocket.md
> +            <img src="https://img.shields.io/github/release-date-pre/{{ developer.username }}/{{ core.repository }}?label=" alt="GitHub Release Date">
Same comment above applies here too.

2022-10-05 12:42 UTC, joshcampbell191 commented on .github/workflows/data_generator.rb
> +        "version"      => normalize_version(metadata["version"]),
It would probably be best to use the `tag_name` attribute in this case. After checking out the repositories, they appear to be pretty consistent across the board with the exception of the Neo Geo core.

2022-10-05 12:47 UTC, joshcampbell191 commented on .github/workflows/data_generator.rb
> +        "date_release" => metadata["date_release"],
The `published_at` value appears to be correct. In the case of the GB / GBC core (https://api.github.com/repos/spiritualized1997/openFPGA-GB-GBC/releases), some assets were published at a later time. I believe it was because some configurations were incorrect. By using the `published_at` date, it would accommodate for that situation.

2022-10-05 16:05 UTC, joshcampbell191 commented on analogue-pocket.md
> +          <td data-order="{{ core.version }}">
I think it's safe to remove the images. They were only used as a means of keeping the page up to date without having to change the content.

2022-10-05 16:06 UTC, joshcampbell191 commented on analogue-pocket.md
> +            <img src="https://img.shields.io/github/release-date-pre/{{ developer.username }}/{{ core.repository }}?label=" alt="GitHub Release Date">
See above comment.

2022-10-07 13:09 UTC, joshcampbell191 commented
What do you think of the following format:
```json
{
    "identifier": "agg23.Arduboy",
    "platform": "Arduboy",
    "repository": {
        "platform": "github",
        "owner": "agg23",
        "name": "analogue-arduboy"
    },
    "prerelease": {
        "tag_name": "v0.9.1",
        "release_date": "2022-09-04T20:45:09Z",
        "assets": [{"platform":"arduboy","extensions":["hex"]}]
    },
    "release": {
        "tag_name": "v0.9.0",
        "release_date": "2022-09-03T20:45:09Z",
        "assets": [{"platform":"arduboy","extensions":["hex"]}]
    }    
}
```

2022-10-08 01:43 UTC, goronfreeman commented
TODO: Make sure you can fetch a release by tag.

2022-10-08 11:32 UTC, joshcampbell191 commented on api/v0/analogue-pocket/cores.json
> +    {%- endif %}
- We could add the `release_date`,`tag_name` and `prerelease` fields.
- We should be listing the latest of the two versions using the `release_date`(if we decide to always show the pre-release).

2022-10-08 11:32 UTC, joshcampbell191 commented on .github/workflows/core_data_generator.rb
> +      return [prerelease, stable] if prerelease["id"] > stable["id"]
Should we return both in all cases? Even if the pre-release isn't later than the release?

2022-10-08 11:32 UTC, joshcampbell191 commented on README.md
> +GET https://joshcampbell191.github.io/openfpga-cores-inventory/api/v1/analogue-pocket/cores.json
Should we create a separate page for the documentation so we can maintain separate versions for the different API endpoints?

2022-10-08 11:32 UTC, joshcampbell191 commented on analogue-pocket.md
> +          <td>{{ metadata.tag_name | remove_first: "v" }}</td>
Do we want it to show the full tag name including the 'v'?

2022-10-08 15:10 UTC, goronfreeman commented on .github/workflows/core_data_generator.rb
> +      return [prerelease, stable] if prerelease["id"] > stable["id"]
I went back and forth on this. From the aspect of the consumer of the API, if pre-releases are turned on, then they can check for the existence of the key if we don't include it. If we do include it, then they'd have to check if the key had any data in it, then compare the tag_name value to the one in the releases key. I went with the first option because it seems to fit the use case I've been thinking about better, but I'm open to handling it a different way if you think we should.

2022-10-08 15:11 UTC, goronfreeman commented on analogue-pocket.md
> +          <td>{{ metadata.tag_name | remove_first: "v" }}</td>
I'm alright with either way. Only reason I stripped it off is to make sorting better. We could leave the "v" in the value in the column and strip it for sorting?

2022-10-08 15:28 UTC, joshcampbell191 commented on analogue-pocket.md
> +          <td>{{ metadata.tag_name | remove_first: "v" }}</td>
How about we display it with the 'v' and sort it without using the `data-sort` attribute?

2022-10-09 01:44 UTC, joshcampbell191 commented on .github/workflows/core_data_generator.rb
> +      return [prerelease, stable] if prerelease["id"] > stable["id"]
Let's leave it as is. Worse case, it won't break anything if we decide to add it at a later time.

2022-10-09 02:00 UTC, joshcampbell191 approved these changes

2022-10-09 02:01 UTC, merged